<style>

.heartbeat {
        -webkit-animation: heartbeat 1.5s ease-in-out infinite both;
        animation: heartbeat 1.5s ease-in-out infinite both
    }

    /* ----------------------------------------------
 * Generated by Animista on 2024-1-31 10:59:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    @-webkit-keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }

        10% {
            -webkit-transform: scale(.91);
            transform: scale(.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in
        }

        17% {
            -webkit-transform: scale(.98);
            transform: scale(.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }

        33% {
            -webkit-transform: scale(.87);
            transform: scale(.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in
        }

        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }
    }

    @keyframes heartbeat {
        from {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-transform-origin: center center;
            transform-origin: center center;
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }

        10% {
            -webkit-transform: scale(.91);
            transform: scale(.91);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in
        }

        17% {
            -webkit-transform: scale(.98);
            transform: scale(.98);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }

        33% {
            -webkit-transform: scale(.87);
            transform: scale(.87);
            -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in
        }

        45% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out
        }
    }
</style>

<section>

  <div class="fixed-bottom flotante animate__bounceIn" style="padding: 10px; left: 46%;">
    <a class="btn btn-primary btn-lg heartbeat" style="padding: 5px; text-align: center;" href="<?php echo base_url('/contactanos');?>">
      Contáctanos
    </a>

  </div>
</section>